[package]
name = "panda"
version = "0.4.0"
description = "An async Rust library for Discord"
keywords = ["discord", "async", "tokio"]
authors = ["Diego Barr√≠a <dbarriapaiva@gmail.com>"]
homepage = "https://github.com/xyaman/panda"
repository = "https://github.com/xyaman/panda"
readme = "README.md"
license = "MIT OR Apache-2.0"
edition = "2018"

[dependencies]
# Serde dependencies
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_repr = "0.1.5"

# Async
futures = "0.3.3"
isahc = { version = "0.9.1", features = ["json"] }

# Websocket / connection
tokio-tungstenite = {version = "0.10.1", features = ["tls"] }
tokio-tls = "0.3.0"

flate2 = { version = "1.0.13", features = ["zlib"], default-features = false }
url = "2.1.0"
log = "0.4.8"

[dependencies.tokio]
version = "0.2.18"
features = ["time", "tcp"]
#features = ["full"]